Version: '2.0.0-SNAPSHOT'

#SQL参数(高一点的版本需要在url加上'useSSL=false')
Sql: false
Url: 'jdbc:mysql://localhost:3306/mc_market?useSSL=false&serverTimezone=UTC'
User: 'root'
Password: '123456'

#是否展示菜单中玩家头颅的皮肤(可能引起网络问题造成网络问题)
DisplaySkin: true
DisplayItemNumber: false

#默认的补签次数，每个月会送的数量
DefaultChance: 2

#周末签到的物品类型
WeekendItem: MAP

#任务进度条
TaskProgress: true

#活跃答题奖励积分
QuizActivity: 1

#奖励，随机取一。
# 签到, 坏奖励, 连续签到一星期奖励, 月连续
SignRewards: []
BadRewards: []
SeriesRewards: []
PerfectRewards: []
# 十分钟, 两小时, 六小时
TenMinutesRewards: []
TwoHoursRewards: []
SixHoursRewards: []


#节日奖励(至少保留一个)
Festival:
  National:
    Month: 10
    Day: 1
    Item: NETHER_STAR
    Reward: give %player% diamond 10
  Christmas:
    Month: 12
    Day: 25
    Item: COOKED_CHICKEN
    Reward: give %player% COOKED_CHICKEN 10
  测试:
    Month: 5
    Day: 23
    Item: NETHER_STAR
    Reward: give %player% diamond 10

#活跃奖励(至少保留一个)
Activity:
  普通:
    Loc: 20
    Item: WHITE_SHULKER_BOX
    Price: 100
    Reward: give %player% diamond 1
  良好:
    Loc: 12
    Item: LIME_SHULKER_BOX
    Price: 300
    Reward: give %player% diamond 5
  精品:
    Loc: 30
    Item: LIGHT_BLUE_SHULKER_BOX
    Price: 500
    Reward: give %player% diamond_block 1
  极品:
    Loc: 14
    Item: PURPLE_SHULKER_BOX
    Price: 800
    Reward: give %player% elytra 1
  至尊:
    Loc: 32
    Item: YELLOW_SHULKER_BOX
    Price: 1000
    Reward: give %player% dragon_head 1
  史诗:
    Loc: 24
    Item: ORANGE_SHULKER_BOX
    Price: 3000
    Reward: give %player% wither_skeleton_skull 1
  神遗:
    Loc: 22
    Item: RED_SHULKER_BOX
    Price: 5000
    Reward: give %player% nether_star 1

#签到奖励(至少保留一个)
#Type 连续 累计
Signin:
  连续3天:
    Loc: 11
    Item: LEATHER_HORSE_ARMOR
    Type: 连续
    Amount: 3
    Reward: give %player% gold_ingot 3
  连续7天:
    Loc: 21
    Item: IRON_HORSE_ARMOR
    Type: 连续
    Amount: 7
    Reward: give %player% emerald 16
  连续15天:
    Loc: 23
    Item: GOLDEN_HORSE_ARMOR
    Type: 连续
    Amount: 15
    Reward: give %player% diamond 20
  本月全勤:
    Loc: 15
    Item: DIAMOND_HORSE_ARMOR
    Type: 连续
    Amount: 30
    Reward: give %player% slime_block 2
  元老玩家:
    Loc: 13
    Item: ENCHANTED_BOOK
    Type: 累计
    Amount: 99
    Reward: give %player% creeper_head 1

#在线奖励(至少保留一个)
#Type 本月、持续 Time单位 M、H、D
Playtime:
  在线8小时:
    Loc: 11
    Item: BRICKS
    Type: 本月
    Time: 8H
    Reward: give %player% gold_ingot 25
  在线3天:
    Loc: 13
    Item: IRON_BLOCK
    Type: 本月
    Time: 3D
    Reward: give %player% emerald 16
  在线一周:
    Loc: 15
    Item: GOLD_BLOCK
    Type: 本月
    Time: 7D
    Reward: give %player% elytra 1
  在线半小时:
    Loc: 29
    Item: BRICK
    Type: 持续
    Time: 30M
    Reward: give %player% gold_ingot 6
  在线2小时:
    Loc: 31
    Item: IRON_INGOT
    Type: 持续
    Time: 2H
    Reward: give %player% diamond 5
  在线5小时:
    Loc: 33
    Item: GOLD_INGOT
    Type: 持续
    Time: 5H
    Reward: give %player% golden_apple 1

#任务列表(至少保留一个, 第一个为新手任务)
#开采⚒ 击杀⚔ 交谈☻
Task:
  初来乍到:
    Item: SLIME_BALL
    Type: newly
    Work: ☻
    Target: 守护者
    Progress: 1
    Reward: 10
  勤劳矿工:
    Item: DIAMOND_ORE
    Type: daily
    Work: ⚒
    Target: DIAMOND_ORE
    Progress: 10
    Reward: 10
  勤劳伐木:
    Item: OAK_LOG
    Type: daily
    Work: ⚒
    Target: 原木
    Progress: 10
    Reward: 10
  亡灵杀手:
    Item: BONE
    Type: daily
    Work: ⚔
    Target: 亡灵
    Progress: 10
    Reward: 10
  猎空杀手:
    Item: ELYTRA
    Type: daily
    Work: ⚔
    Target: 飞行
    Progress: 10
    Reward: 10
  发家致富:
    Item: OAK_LOG
    Type: normal
    Work: ⚒
    Target: 原木
    Progress: 10
    Reward: 10
  我的家园:
    Item: SLIME_BALL
    Type: normal
    Work: ◈
    Target: Plot
    Progress: 1
    Reward: 10

#任务对象(至少保留一个)
Object:
  原木: ACACIA_LOG,BIRCH_LOG,DARK_OAK_LOG,JUNGLE_LOG,OAK_LOG
  亡灵: ZOMBIE,SKELETON
