main: com.fireflyest.activity.Activity
name: Activity
version: 1.0-SNAPSHOT
description: 活跃度插件，作者QQ746969484(备注来意)
api-version: 1.13
authors: [Fireflyest]
website: https://www.mcbbs.net/thread-906368-1-1.html
depend: [Vault,Gui]

commands:
  activity:
    description: 打开界面
    usage: /activity <help>
  sign:
    description: 签到
    usage: /sign
  playtime:
    description: 在线时长
    usage: /playtime
  quiz:
    description: 问答
    usage: /quiz [quiz] [rightOption] [option]...
  reward:
    description: 奖励
    usage: /reward [add|remove] [name]
    permission: op
  task:
    description: 活动
    usage: /task [add|remove] [name] <deadline>
    permission: op
permissions:
  activity.chance:
    description: 给予补签机会
    default: op
  activity.add:
    description: 给予活跃度
    default: op
  activity.rank:
    description: 查看排行榜
    default: op
  activity.quiz:
    description: 发起抢答
    default: op
  activity.reward:
    description: 奖励
    default: op
  activity.task:
    description: 活动
    default: op
  activity.create:
    description: 创建牌子
    default: op
